export const {
  PORT,
  SALT_ROUNDS,
  NODE_ENV,
  ALLOWED_FRONTEND_URL,
  RESEND_EMAIL,
  RESEND_API_KEY,
  JWT_SECRET_KEY,
  MONGODB_URI,
  MONGODB_LOCAL,

  //Nodemailer
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_USER,
  EMAIL_PASS,

  //Cloudinary
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET
} =  process.env;